travis:
  secure:
    BINSTAR_TOKEN: hyIdtfKBbLzf3bu372A9mRjKRUtmRgSXUzk3G8L5rLXhmHtq8uHtm8Z9tPAKSuYwIuIgLwlEv1tWBFUGwZ4SoI1FKVrSdL8UrNNa2Rj/Cm0Wg0a77zUkhFP64xmB70r3YBZ8yKS8E/vQce238bk0FKEBDkQExL4Y41Nkgl7avPehWl8ot8o1GJJORSBpnaHd0/HugLR9RvFhBdTgWqMayA9jpscI1hqiiGDwQIQFihYc+nx6D8A4tVSp1w7lnYgnB/EEyGivxnNATJE+klJxZv3mQIFyu4gy1CNjoeAz455s2l+FVYhnLn63AcmmGdKLANGKeTCXUi1PhLqfq67mL+0ydos61Nho/m1qPjwJvUM+n4wbR9MhnCSbj8/2avo4bmFvEoLMh4qFdFzvXUSJQGB64BDE+vi3oE+jHUKKT5Qa/h/u9Z3lS7A08FsF67QO0oEap1bCyLwL8XFrziBRFB4SstXwofGOu1fsYFc8kIbqg2M0mOWxF4rzPV+ylUsSnZBwl+pkWYejB1TqQuK7jTv8BZwNSPyFc1u/yi1jqXIgs9P+48MzELaAWsHrl3RnoY+zxr8wFCNTQvXYjSvfF2PEkFflU63SqRn1nmRMpcP89E4HD0rJf1q9fvJ1s44izsvV/5ppxO3yCw6fzGMKU8EEQHl82H1EOoSddr8xaN4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
